### ISSUE TITLE
I'd like to join the Open Traits Network

### ISSUE THREAD

**Issue by LoicChr** [open-traits-network/open-traits-network.github.io#106]
Please update the template below and click "Submit" to let us know you'd like to become a member of the Open Traits Network. Please allow for some time for @open-traits-network/editors to review your request.

```
---
layout: member
id: loic-chalmandrier
name: Loïc Chalmandrier
email: loic.chalmandrier@canterbury.ac.nz
homepage: http://lchalmandrier.legtux.org/research/
lat: -43.523351 
long: 172.584973
affiliation: University of Regensburg, Germany and  University of Canterbury, New Zealand
github: LoicChr
---
Loïc is a post-doctoral researcher currently located in the University of Canterbury.

## Collaboration statement
My research focuses on the analysis of plant communities structure, mostly through the lens of functional traits. More precisely, I am developing new statistical methodologies designed to take full advantage of functional trait data to understand plant coexistence and dynamics. 

I can offer expertise in those areas and  I am also happy to more generally participate to the Open Traits initiative.

```

Editors @open-traits-network/editors: please see https://github.com/open-traits-network/open-traits-network.github.io/tree/master/_members#readme for information on registration process.

**Comment by rachaelgallagher** [comment]
Hi @LoicChr - thanks for joining the OTN! It's great to have new members and we are always keen for assistance in welcoming others. You said you are keen to help with participating the OTN - one way to do this is to learn how to become an editor so that you can add new profiles and welcome new people on board. If you'd like to do that please let us know! @rachaelgallagher @jhpoelen @bmaitner
