### ISSUE TITLE
Hey guys, I'd be glad to become an editor of OpenTraits. What do I need to do to become one?

### ISSUE THREAD

**Issue by RobSalGo** [open-traits-network/open-traits-network.github.io#150]
Hi! 

Thank you for your interest in the Open Traits Network.

Please enter your question, comment or suggestion. Then click "submit" to let us know. Please allow for some time for a response.

**Comment by RobSalGo** [comment]
hey guys, I'd be glad to become an editor. What does one have to do to become one?

**Comment by jhpoelen** [comment]
@RobSalGo Thanks for sharing your interest in becoming an open traits network editor! To become an editor, there's two things might want to do:

1. suggest familiarize yourself with the editorial process of dataset/member registration. See https://github.com/open-traits-network/open-traits-network.github.io/blob/master/_datasets/README.md and https://github.com/open-traits-network/open-traits-network.github.io/blob/master/_members/README.md for respective process descriptions.
2. pick one of the open issues (e.g., https://github.com/open-traits-network/open-traits-network.github.io/issues/79) and register some datasets

Also, I am sure there's plenty of room for improvements (e.g., improve metadata, apply corrections, update process, update documentation), and that you have some great ideas to help make the Open Traits Network be more useful to help do collaborative research. 

Once you feel comfortable with the editorial process, you can ask to get admin access to the registries, so that you can merge pull requests yourself.

Some of your colleagues like @BErfanian and @JonathonMifsud have recently started editing, so perhaps they also have some suggestions.

Hope this helps, and please holler if you have any questions.

**Comment by BErfanian** [comment]
@RobSalGo Hi and welcome.
Let me know if there's anything I can help you with.

**Comment by jhpoelen** [comment]
hey @RobSalGo - just to check-in with you about your desire to become a OTN editors. I noticed that you haven't yet made any edits . Please let me know how I can help get you started.

**Comment by jhpoelen** [comment]
@RobSalGo am closing issue for now, please feel free to reach out to any of the OTN editors https://opentraits.org/editors if you'd like to contribute as an editor.

**Comment by RobSalGo** [comment]
Apols for the delay, Jorrit. Due to my current health condition (over 12 months of long COVID) I am unable to engage in this specific academic opportunity at the moment. I’ll get back to you when things improve.
Thanks for your understanding
Rob S-G

"Aliud iter ad prosperitatem nos est: id est omnibus rebus vincere"
.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.
Dr. Rob Salguero-Gómez

Associate Professor, Department of Zoology, University of Oxford
Tutorial Fellow, Pembroke College
NERC Independent Research Fellow
Honorary Fellow, Centre of Excellence in Environmental Decisions, University of Queensland, Australia
Guest Visitor, Max Planck Institute for Demographic Research, Germany
https://www.salgo.ox.ac.uk/
www.compadre-db.org

On 26 Mar 2021, at 14:36, Jorrit Poelen ***@***.******@***.***>> wrote:



@RobSalGo<https://github.com/RobSalGo> am closing issue for now, please feel free to reach out to any of the OTN editors https://opentraits.org/editors if you'd like to contribute as an editor.

**Comment by jhpoelen** [comment]
@RobSalGo thanks for responding. Whenever you are able and willing, please feel free to reach out. No rush!
