### ISSUE TITLE
Please add Sharkipedia to the OTN dataset registry

### ISSUE THREAD

**Issue by creeas** [open-traits-network/open-traits-network.github.io#170]
Please fill out the template below and click "submit" to request a trait dataset to the Open Traits Network. Please allow for some time for @open-traits-network/editors to review your submission.

```
---
layout: dataset
id: Sharkipedia
name: Sharkipedia
datasetDOI_URL: https://www.sharkipedia.org
contactName: Christopher Mull
contactEmail: creeas@gmail.com
license: CC BY
traitList: 3034 measurements of 49 traits covering 105 species (continuously updated)
higherGeography: Global
decimalLatitude: All
decimalLongitude: All
taxon: Chondrichthyes
eventDate: about 1980 to current
paperDOIcitation: In Prep
description: An open-access curated database of shark and ray (all chondrichthyes) life history traits and abundance time-series.
taxaList: ~1,200 species based on current taxonomic status of chindrichthyes. See vertlife.org/sharktree for full taxonomic informtion.
usefulClasses: Empirical and model derived measurement of life history traits and abundance. All measurements MUST be traced to a valid peer-reviewed reference. Collaborating with shark-references.org for reference database. 
dataStandard: Standardization of traits according to procedures (https://www.sharkipedia.org/procedure) and taxonomy according to sharktrees (http://vertlife.org/sharktree/taxonomy/)
standardizationScripts: 
webpage: https://www.sharkipedia.org
---
```

Editors @open-traits-network/editors: please see https://github.com/open-traits-network/open-traits-network.github.io/tree/master/_datasets#readme for information on registration process.

**Comment by jhpoelen** [comment]
hey @creeas - thanks for registering Sharkipedia with the Open Traits Network. You can find the OTN dataset page at https://opentraits.org/datasets/sharkipedia . If you'd like to add or otherwise update the page, please use the "edit" link to recreate a pull request or create a new issue with description of what you'd like to change.
Excellent to see that your work was part inspired CoralTraits http://opentraits.org/datasets/coral-traits by @jmadin et al. 

Welcome to OTN!
